/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of ErrorResponse
 */
interface ErrorResponse {
  /** Error type identifier */
  error: string;
  /** Human-readable error message */
  message: string;
  /** Unique identifier for the request, useful for debugging and support */
  requestId?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ErrorResponseError extends ApiError<ErrorResponse> {}
