/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
  string,
} from '../../schema.js';
import {
  FeeTokenEnriched,
  feeTokenEnrichedSchema,
} from '../feeTokenEnriched.js';

/** This is a container type for one-of types. */
export type ChainDetailsFeeTokens = string[] | FeeTokenEnriched[];

export const chainDetailsFeeTokensSchema: Schema<ChainDetailsFeeTokens> = lazy(
  () => oneOf([array(string()), array(feeTokenEnrichedSchema)])
);

export namespace ChainDetailsFeeTokens {
  /**
   * Validation method to narrow down union type to string[] type case.
   *
   * This is Array of String case.
   */
  export function isArrayOfString(value: unknown): value is string[] {
    return (
      Array.isArray(value) && value.every((item) => typeof item === 'string')
    );
  }

  /**
   * Validation method to narrow down union type to FeeTokenEnriched[] type case.
   *
   * This is Array of FeeTokenEnriched case.
   */
  export function isArrayOfFeeTokenEnriched(
    value: unknown
  ): value is FeeTokenEnriched[] {
    if (!Array.isArray(value)) {
      return false;
    }
    return isMappedValueValidForSchema(value, array(feeTokenEnrichedSchema));
  }
}
