/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ChainApiResponse,
  chainApiResponseSchema,
} from '../models/chainApiResponse.js';
import {
  EnrichFeeTokens,
  enrichFeeTokensSchema,
} from '../models/enrichFeeTokens.js';
import { Environment3, environment3Schema } from '../models/environment3.js';
import { Family, familySchema } from '../models/family.js';
import { OutputKey, outputKeySchema } from '../models/outputKey.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorResponseError } from '../errors/errorResponseError.js';

export class ChainsApi extends BaseApi {
  /**
   * Returns information about Cross-Chain Interoperability Protocol (CCIP) chains across different
   * blockchain families (EVM, Solana, Aptos)
   *
   * @param environment     The network environment to query
   * @param chainId         Filter by chain ID (e.g., "1" for Ethereum, "56" for BSC, or a Solana
   *                                           pubkey)
   * @param selector        Filter by CCIP chain selector. Multiple selectors can be specified
   *                                           using comma-separated values
   * @param internalId      Filter by internal chain identifier. Multiple IDs can be specified
   *                                           using comma-separated values (e.g., "ethereum-mainnet,bsc-mainnet")
   * @param outputKey       Key to use for organizing the response data
   * @param enrichFeeTokens When set to 'true', returns detailed fee token information including
   *                                           addresses, names, and decimals instead of just symbol strings
   * @param search          Unified search query. Automatically detects query type: selector (>17
   *                                           digits), chainId (≤17 digits or Solana base58 hash), internalId (kebab-
   *                                           case), or displayName (fuzzy text search). Cannot be combined with
   *                                           chainId, selector, or internalId filters.
   * @param family          Filter results by chain family. Only effective when using the search
   *                                           parameter.
   * @return Response from the API call
   */
  async getChains(
    environment: Environment3,
    chainId?: string,
    selector?: string,
    internalId?: string,
    outputKey?: OutputKey,
    enrichFeeTokens?: EnrichFeeTokens,
    search?: string,
    family?: Family,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ChainApiResponse>> {
    const req = this.createRequest('GET', '/chains');
    const mapped = req.prepareArgs({
      environment: [environment, environment3Schema],
      chainId: [chainId, optional(string())],
      selector: [selector, optional(string())],
      internalId: [internalId, optional(string())],
      outputKey: [outputKey, optional(outputKeySchema)],
      enrichFeeTokens: [enrichFeeTokens, optional(enrichFeeTokensSchema)],
      search: [search, optional(string())],
      family: [family, optional(familySchema)],
    });
    req.query('environment', mapped.environment);
    req.query('chainId', mapped.chainId);
    req.query('selector', mapped.selector);
    req.query('internalId', mapped.internalId);
    req.query('outputKey', mapped.outputKey);
    req.query('enrichFeeTokens', mapped.enrichFeeTokens);
    req.query('search', mapped.search);
    req.query('family', mapped.family);
    req.throwOn(400, ErrorResponseError, 'Invalid request parameters');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    return req.callAsJson(chainApiResponseSchema, requestOptions);
  }
}
