/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Environment3, environment3Schema } from '../models/environment3.js';
import {
  LaneApiResponse,
  laneApiResponseSchema,
} from '../models/laneApiResponse.js';
import { OutputKey, outputKeySchema } from '../models/outputKey.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorResponseError } from '../errors/errorResponseError.js';

export class LanesApi extends BaseApi {
  /**
   * Returns information about Cross-Chain Interoperability Protocol (CCIP) lanes between supported
   * chains. Each lane represents a unidirectional connection from a source chain to a destination chain,
   * with associated onRamp and offRamp contracts and supported tokens.
   *
   * @param environment           The network environment to query
   * @param sourceChainId         Filter by source chain ID. Multiple chain IDs can be specified using
   *                                              comma-separated values
   * @param destinationChainId    Filter by destination chain ID. Multiple chain IDs can be specified
   *                                              using comma-separated values
   * @param sourceSelector        Filter by source chain CCIP selector. Multiple selectors can be
   *                                              specified using comma-separated values
   * @param destinationSelector   Filter by destination chain CCIP selector. Multiple selectors can be
   *                                              specified using comma-separated values
   * @param sourceInternalId      Filter by source chain internal identifier. Multiple IDs can be
   *                                              specified using comma-separated values
   * @param destinationInternalId Filter by destination chain internal identifier. Multiple IDs can be
   *                                              specified using comma-separated values
   * @param version               Filter by lane version. Only lanes where both onRamp and offRamp
   *                                              match the specified version will be returned
   * @param outputKey             Key format to use for organizing the lane keys in the response
   * @return Response from the API call
   */
  async getLanes(
    environment: Environment3,
    sourceChainId?: string,
    destinationChainId?: string,
    sourceSelector?: string,
    destinationSelector?: string,
    sourceInternalId?: string,
    destinationInternalId?: string,
    version?: string,
    outputKey?: OutputKey,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<LaneApiResponse>> {
    const req = this.createRequest('GET', '/lanes');
    const mapped = req.prepareArgs({
      environment: [environment, environment3Schema],
      sourceChainId: [sourceChainId, optional(string())],
      destinationChainId: [destinationChainId, optional(string())],
      sourceSelector: [sourceSelector, optional(string())],
      destinationSelector: [destinationSelector, optional(string())],
      sourceInternalId: [sourceInternalId, optional(string())],
      destinationInternalId: [destinationInternalId, optional(string())],
      version: [version, optional(string())],
      outputKey: [outputKey, optional(outputKeySchema)],
    });
    req.query('environment', mapped.environment);
    req.query('sourceChainId', mapped.sourceChainId);
    req.query('destinationChainId', mapped.destinationChainId);
    req.query('sourceSelector', mapped.sourceSelector);
    req.query('destinationSelector', mapped.destinationSelector);
    req.query('sourceInternalId', mapped.sourceInternalId);
    req.query('destinationInternalId', mapped.destinationInternalId);
    req.query('version', mapped.version);
    req.query('outputKey', mapped.outputKey);
    req.throwOn(400, ErrorResponseError, 'Bad request - invalid parameters');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    return req.callAsJson(laneApiResponseSchema, requestOptions);
  }
}
