/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Environment3, environment3Schema } from '../models/environment3.js';
import { OutputKey, outputKeySchema } from '../models/outputKey.js';
import {
  TokenApiResponse,
  tokenApiResponseSchema,
} from '../models/tokenApiResponse.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorResponseError } from '../errors/errorResponseError.js';

export class TokensApi extends BaseApi {
  /**
   * Returns information about Cross-Chain Interoperability Protocol (CCIP) supported tokens. The
   * response includes token details organized by token symbol, with chain-specific information nested
   * under each token and indexed by chain ID or selector (depending on the outputKey parameter).
   *
   * @param environment The network environment to query
   * @param tokenId     Filter by token canonical identifier (e.g., "LINK" for Chainlink token, or
   *                                    "LINK,ETH" for multiple tokens)
   * @param chainId     Filter by chain ID where the token is supported (e.g., "1" for Ethereum, or "1,
   *                                    56" for Ethereum and BSC)
   * @param outputKey   Key to use for organizing the response data
   * @return Response from the API call
   */
  async getTokens(
    environment: Environment3,
    tokenId?: string,
    chainId?: string,
    outputKey?: OutputKey,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TokenApiResponse>> {
    const req = this.createRequest('GET', '/tokens');
    const mapped = req.prepareArgs({
      environment: [environment, environment3Schema],
      tokenId: [tokenId, optional(string())],
      chainId: [chainId, optional(string())],
      outputKey: [outputKey, optional(outputKeySchema)],
    });
    req.query('environment', mapped.environment);
    req.query('token_id', mapped.tokenId);
    req.query('chain_id', mapped.chainId);
    req.query('outputKey', mapped.outputKey);
    req.throwOn(400, ErrorResponseError, 'Invalid request parameters');
    req.throwOn(500, ErrorResponseError, 'Internal server error');
    return req.callAsJson(tokenApiResponseSchema, requestOptions);
  }
}
