/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChainInfoChainId,
  chainInfoChainIdSchema,
} from './containers/chainInfoChainId.js';

/** Chain information used in lane endpoints. Note: chainType and chainFamily are intentionally excluded from this schema for API responses. */
export interface ChainInfo {
  /** Identifier of the chain (numeric for EVM chains, string for Solana/Aptos chains) */
  chainId: ChainInfoChainId;
  /** Human-readable name of the chain */
  displayName: string;
  /** CCIP chain selector as a string */
  selector: string;
  /** Internal identifier used in configuration */
  internalId: string;
  additionalProperties?: Record<string, unknown>;
}

export const chainInfoSchema: Schema<ChainInfo> = lazy(() =>
  typedExpandoObject(
    {
      chainId: ['chainId', chainInfoChainIdSchema],
      displayName: ['displayName', string()],
      selector: ['selector', string()],
      internalId: ['internalId', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
