/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ChainConfigError {
  /** Chain ID of the failed configuration */
  chainId: number;
  /** Network identifier of the failed configuration */
  networkId: string;
  /** Reason for the configuration failure */
  reason: string;
  /** List of missing required fields */
  missingFields: string[];
  additionalProperties?: Record<string, unknown>;
}

export const chainConfigErrorSchema: Schema<ChainConfigError> = typedExpandoObject(
  {
    chainId: ['chainId', number()],
    networkId: ['networkId', string()],
    reason: ['reason', string()],
    missingFields: ['missingFields', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
