/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChainFamily, chainFamilySchema } from './chainFamily.js';
import { ChainType, chainTypeSchema } from './chainType.js';
import {
  ChainDetailsChainId,
  chainDetailsChainIdSchema,
} from './containers/chainDetailsChainId.js';
import {
  ChainDetailsFeeTokens,
  chainDetailsFeeTokensSchema,
} from './containers/chainDetailsFeeTokens.js';

export interface ChainDetails {
  /** Identifier of the chain (numeric for EVM chains, string for Solana/Aptos chains) */
  chainId: ChainDetailsChainId;
  /** Human-readable name of the chain. For supported chains, this comes from configuration. For unsupported chains, it is derived from the internalId. */
  displayName: string;
  /** CCIP chain selector */
  selector: string;
  /** Internal identifier for the chain */
  internalId: string;
  /** Fee tokens - either as string symbols or enriched objects with addresses. Empty array for unsupported chains. */
  feeTokens: ChainDetailsFeeTokens;
  /** CCIP Router contract address. Empty string for unsupported chains. */
  router: string;
  /** Risk Management Network contract address. Empty string for unsupported chains. */
  rmn: string;
  /** Type of blockchain */
  chainType: ChainType;
  /** Blockchain family grouping */
  chainFamily: ChainFamily;
  /** Whether this chain is fully supported with complete configuration. Unsupported chains have minimal details (empty router, rmn, feeTokens). */
  supported: boolean;
  /** Registry Module contract address (EVM chains only) */
  registryModule?: string;
  /** Token Admin Registry contract address (EVM and Aptos chains) */
  tokenAdminRegistry?: string;
  /** Token Pool Factory contract address (EVM chains only) */
  tokenPoolFactory?: string;
  /** Fee Quoter address (Solana chains only) */
  feeQuoter?: string;
  /** MCMS (Multi-Chain Management Service) address (Aptos chains only) */
  mcms?: string;
  additionalProperties?: Record<string, unknown>;
}

export const chainDetailsSchema: Schema<ChainDetails> = lazy(() =>
  typedExpandoObject(
    {
      chainId: ['chainId', chainDetailsChainIdSchema],
      displayName: ['displayName', string()],
      selector: ['selector', string()],
      internalId: ['internalId', string()],
      feeTokens: ['feeTokens', chainDetailsFeeTokensSchema],
      router: ['router', string()],
      rmn: ['rmn', string()],
      chainType: ['chainType', chainTypeSchema],
      chainFamily: ['chainFamily', chainFamilySchema],
      supported: ['supported', boolean()],
      registryModule: ['registryModule', optional(string())],
      tokenAdminRegistry: ['tokenAdminRegistry', optional(string())],
      tokenPoolFactory: ['tokenPoolFactory', optional(string())],
      feeQuoter: ['feeQuoter', optional(string())],
      mcms: ['mcms', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
