/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MEnvironment, mEnvironmentSchema } from './mEnvironment.js';
import { SearchType, searchTypeSchema } from './searchType.js';

export interface ChainMetadata {
  /** The network environment */
  environment: MEnvironment;
  /** ISO timestamp of the response */
  timestamp: string;
  /** Unique identifier for the request */
  requestId: string;
  /** Number of chains ignored due to configuration issues */
  ignoredChainCount: number;
  /** Number of valid chains in the response */
  validChainCount: number;
  /** The search query that was used (only present when search parameter was provided) */
  searchQuery?: string;
  /** The detected type of search query. 'selector' for CCIP selectors (>17 digits), 'chainId' for chain IDs (≤17 digits or Solana base58), 'internalId' for kebab-case identifiers, 'displayName' for fuzzy text search. */
  searchType?: SearchType;
  additionalProperties?: Record<string, unknown>;
}

export const chainMetadataSchema: Schema<ChainMetadata> = typedExpandoObject(
  {
    environment: ['environment', mEnvironmentSchema],
    timestamp: ['timestamp', string()],
    requestId: ['requestId', string()],
    ignoredChainCount: ['ignoredChainCount', number()],
    validChainCount: ['validChainCount', number()],
    searchQuery: ['searchQuery', optional(string())],
    searchType: ['searchType', optional(searchTypeSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
