/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ChainConfigError,
  chainConfigErrorSchema,
} from './chainConfigError.js';
import { ChainMetadata, chainMetadataSchema } from './chainMetadata.js';
import { Data, dataSchema } from './data.js';

export interface ChainApiResponse {
  metadata: ChainMetadata;
  /** Chain details grouped by chain family */
  data: Data;
  /** List of chains that could not be configured */
  ignored: ChainConfigError[];
  additionalProperties?: Record<string, unknown>;
}

export const chainApiResponseSchema: Schema<ChainApiResponse> = lazy(() =>
  typedExpandoObject(
    {
      metadata: ['metadata', chainMetadataSchema],
      data: ['data', dataSchema],
      ignored: ['ignored', array(chainConfigErrorSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
