/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChainDetails, chainDetailsSchema } from './chainDetails.js';

/** Chain details grouped by chain family */
export interface Data {
  /** EVM chain details keyed by the specified output key */
  evm?: Record<string, ChainDetails>;
  /** Solana chain details keyed by the specified output key */
  solana?: Record<string, ChainDetails>;
  /** Aptos chain details keyed by the specified output key */
  aptos?: Record<string, ChainDetails>;
  /** Sui chain details keyed by the specified output key */
  sui?: Record<string, ChainDetails>;
  /** Tron chain details keyed by the specified output key */
  tron?: Record<string, ChainDetails>;
  /** Canton chain details keyed by the specified output key */
  canton?: Record<string, ChainDetails>;
  /** TON chain details keyed by the specified output key */
  ton?: Record<string, ChainDetails>;
  /** Stellar chain details keyed by the specified output key */
  stellar?: Record<string, ChainDetails>;
  /** Starknet chain details keyed by the specified output key */
  starknet?: Record<string, ChainDetails>;
  additionalProperties?: Record<string, unknown>;
}

export const dataSchema: Schema<Data> = lazy(() =>
  typedExpandoObject(
    {
      evm: ['evm', optional(dict(chainDetailsSchema))],
      solana: ['solana', optional(dict(chainDetailsSchema))],
      aptos: ['aptos', optional(dict(chainDetailsSchema))],
      sui: ['sui', optional(dict(chainDetailsSchema))],
      tron: ['tron', optional(dict(chainDetailsSchema))],
      canton: ['canton', optional(dict(chainDetailsSchema))],
      ton: ['ton', optional(dict(chainDetailsSchema))],
      stellar: ['stellar', optional(dict(chainDetailsSchema))],
      starknet: ['starknet', optional(dict(chainDetailsSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
