/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EnrichFeeTokens
 */
export enum EnrichFeeTokens {
  True = 'true',
  False = 'false',
}

/**
 * Schema for EnrichFeeTokens
 */
export const enrichFeeTokensSchema: Schema<EnrichFeeTokens> = stringEnum(
  EnrichFeeTokens
);
