/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Environment3
 */
export enum Environment3 {
  Mainnet = 'mainnet',
  Testnet = 'testnet',
}

/**
 * Schema for Environment3
 */
export const environment3Schema: Schema<Environment3> = stringEnum(
  Environment3
);
