/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Family
 */
export enum Family {
  Evm = 'evm',
  Solana = 'solana',
  Aptos = 'aptos',
  Sui = 'sui',
  Tron = 'tron',
  Canton = 'canton',
  Ton = 'ton',
  Stellar = 'stellar',
  Starknet = 'starknet',
}

/**
 * Schema for Family
 */
export const familySchema: Schema<Family> = stringEnum(Family);
