/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FeeTokenEnriched {
  /** Token symbol (e.g., LINK, WETH) */
  symbol: string;
  /** Token name (e.g., Chainlink, Wrapped Ether) */
  name: string;
  /** Token contract address on this chain */
  address: string;
  /** Number of decimals for the token */
  decimals: number;
  additionalProperties?: Record<string, unknown>;
}

export const feeTokenEnrichedSchema: Schema<FeeTokenEnriched> = typedExpandoObject(
  {
    symbol: ['symbol', string()],
    name: ['name', string()],
    address: ['address', string()],
    decimals: ['decimals', number()],
  },
  'additionalProperties',
  optional(unknown())
);
