/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MEnvironment, mEnvironmentSchema } from './mEnvironment.js';

export interface LaneMetadata {
  /** The network environment */
  environment: MEnvironment;
  /** ISO timestamp of the response */
  timestamp: string;
  /** Unique identifier for the request */
  requestId: string;
  /** Number of lanes ignored due to configuration issues */
  ignoredLaneCount: number;
  /** Number of valid lanes in the response */
  validLaneCount: number;
  additionalProperties?: Record<string, unknown>;
}

export const laneMetadataSchema: Schema<LaneMetadata> = typedExpandoObject(
  {
    environment: ['environment', mEnvironmentSchema],
    timestamp: ['timestamp', string()],
    requestId: ['requestId', string()],
    ignoredLaneCount: ['ignoredLaneCount', number()],
    validLaneCount: ['validLaneCount', number()],
  },
  'additionalProperties',
  optional(unknown())
);
