/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { LaneConfigError, laneConfigErrorSchema } from './laneConfigError.js';
import { LaneDetails, laneDetailsSchema } from './laneDetails.js';
import { LaneMetadata, laneMetadataSchema } from './laneMetadata.js';

export interface LaneApiResponse {
  metadata: LaneMetadata;
  /** Lane data organized by dynamic lane keys (e.g., '1_to_56', 'ethereum-mainnet_to_polygon-mainnet') */
  data: Record<string, LaneDetails>;
  /** List of lanes that could not be configured */
  ignored: LaneConfigError[];
  additionalProperties?: Record<string, unknown>;
}

export const laneApiResponseSchema: Schema<LaneApiResponse> = lazy(() =>
  typedExpandoObject(
    {
      metadata: ['metadata', laneMetadataSchema],
      data: ['data', dict(laneDetailsSchema)],
      ignored: ['ignored', array(laneConfigErrorSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
