/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ChainInfo, chainInfoSchema } from './chainInfo.js';
import { OffRamp, offRampSchema } from './offRamp.js';
import { OnRamp, onRampSchema } from './onRamp.js';

export interface LaneDetails {
  /** Chain information used in lane endpoints. Note: chainType and chainFamily are intentionally excluded from this schema for API responses. */
  sourceChain: ChainInfo;
  /** Chain information used in lane endpoints. Note: chainType and chainFamily are intentionally excluded from this schema for API responses. */
  destinationChain: ChainInfo;
  onRamp: OnRamp;
  offRamp: OffRamp;
  /** List of supported token keys (e.g., LINK, CCIP-BnM, USDC) */
  supportedTokens: string[];
  additionalProperties?: Record<string, unknown>;
}

export const laneDetailsSchema: Schema<LaneDetails> = lazy(() =>
  typedExpandoObject(
    {
      sourceChain: ['sourceChain', chainInfoSchema],
      destinationChain: ['destinationChain', chainInfoSchema],
      onRamp: ['onRamp', onRampSchema],
      offRamp: ['offRamp', offRampSchema],
      supportedTokens: ['supportedTokens', array(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
