/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LaneConfigError {
  /** Source chain identifier that failed configuration */
  sourceChain: string;
  /** Destination chain identifier that failed configuration */
  destinationChain: string;
  /** Human-readable reason for the configuration failure */
  reason: string;
  /** List of missing or invalid configuration fields */
  missingFields: string[];
  additionalProperties?: Record<string, unknown>;
}

export const laneConfigErrorSchema: Schema<LaneConfigError> = typedExpandoObject(
  {
    sourceChain: ['sourceChain', string()],
    destinationChain: ['destinationChain', string()],
    reason: ['reason', string()],
    missingFields: ['missingFields', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
