/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OffRamp {
  /** OffRamp contract address */
  address: string;
  /** Normalized semantic version of the OffRamp contract */
  version: string;
  additionalProperties?: Record<string, unknown>;
}

export const offRampSchema: Schema<OffRamp> = typedExpandoObject(
  { address: ['address', string()], version: ['version', string()] },
  'additionalProperties',
  optional(unknown())
);
