/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OnRamp {
  /** OnRamp contract address */
  address: string;
  /** Normalized semantic version of the OnRamp contract */
  version: string;
  /** Whether the OnRamp enforces out-of-order execution */
  enforceOutOfOrder?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const onRampSchema: Schema<OnRamp> = typedExpandoObject(
  {
    address: ['address', string()],
    version: ['version', string()],
    enforceOutOfOrder: ['enforceOutOfOrder', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
