/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OutputKey
 */
export enum OutputKey {
  ChainId = 'chainId',
  Selector = 'selector',
  InternalId = 'internalId',
}

/**
 * Schema for OutputKey
 */
export const outputKeySchema: Schema<OutputKey> = stringEnum(OutputKey);
