/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PoolType
 */
export enum PoolType {
  LockRelease = 'lockRelease',
  BurnMint = 'burnMint',
  Usdc = 'usdc',
  FeeTokenOnly = 'feeTokenOnly',
}

/**
 * Schema for PoolType
 */
export const poolTypeSchema: Schema<PoolType> = stringEnum(PoolType);
