/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SearchType
 */
export enum SearchType {
  Selector = 'selector',
  ChainId = 'chainId',
  InternalId = 'internalId',
  DisplayName = 'displayName',
}

/**
 * Schema for SearchType
 */
export const searchTypeSchema: Schema<SearchType> = stringEnum(SearchType);
