/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TokenChainDataChainId,
  tokenChainDataChainIdSchema,
} from './containers/tokenChainDataChainId.js';
import { PoolType, poolTypeSchema } from './poolType.js';

export interface TokenChainData {
  /** Identifier of the chain (numeric for EVM chains, string for Solana/Aptos chains) */
  chainId: TokenChainDataChainId;
  /** Human-readable name of the chain */
  chainName: string;
  /** Token contract address on this chain */
  tokenAddress: string;
  /** Number of decimals used for the token */
  decimals: number;
  /** Type of pool for this token */
  poolType: PoolType;
  /** Token pool contract address (if applicable) */
  poolAddress: string;
  /** Name of the token */
  name?: string;
  /** Symbol of the token */
  symbol?: string;
  /** Destination chains this token can be sent to */
  destinations?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const tokenChainDataSchema: Schema<TokenChainData> = lazy(() =>
  typedExpandoObject(
    {
      chainId: ['chainId', tokenChainDataChainIdSchema],
      chainName: ['chainName', string()],
      tokenAddress: ['tokenAddress', string()],
      decimals: ['decimals', number()],
      poolType: ['poolType', poolTypeSchema],
      poolAddress: ['poolAddress', string()],
      name: ['name', optional(string())],
      symbol: ['symbol', optional(string())],
      destinations: ['destinations', optional(array(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
