/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface TokenConfigError {
  /** Token symbol */
  symbol: string;
  /** Reason for the configuration error */
  reason: string;
  /** List of missing required fields */
  missingFields: string[];
  additionalProperties?: Record<string, unknown>;
}

export const tokenConfigErrorSchema: Schema<TokenConfigError> = typedExpandoObject(
  {
    symbol: ['symbol', string()],
    reason: ['reason', string()],
    missingFields: ['missingFields', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
