/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MEnvironment, mEnvironmentSchema } from './mEnvironment.js';

export interface TokenMetadata {
  /** The network environment */
  environment: MEnvironment;
  /** ISO timestamp of the response */
  timestamp: string;
  /** Unique identifier for the request */
  requestId: string;
  /** Number of tokens ignored due to configuration issues */
  ignoredTokenCount: number;
  /** Number of valid tokens in the response */
  validTokenCount: number;
  additionalProperties?: Record<string, unknown>;
}

export const tokenMetadataSchema: Schema<TokenMetadata> = typedExpandoObject(
  {
    environment: ['environment', mEnvironmentSchema],
    timestamp: ['timestamp', string()],
    requestId: ['requestId', string()],
    ignoredTokenCount: ['ignoredTokenCount', number()],
    validTokenCount: ['validTokenCount', number()],
  },
  'additionalProperties',
  optional(unknown())
);
