/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TokenChainInfo, tokenChainInfoSchema } from './tokenChainInfo.js';

export interface TokenDetails {
  /** Token symbol identifier */
  symbol: string;
  /** Available token lanes: source chain to array of destination chains */
  lanes?: Record<string, unknown>;
  /** Detailed information about the token on each chain */
  chains: TokenChainInfo[];
  additionalProperties?: Record<string, unknown>;
}

export const tokenDetailsSchema: Schema<TokenDetails> = lazy(() =>
  typedExpandoObject(
    {
      symbol: ['symbol', string()],
      lanes: ['lanes', optional(dict(unknown()))],
      chains: ['chains', array(tokenChainInfoSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
