/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TokenChainData, tokenChainDataSchema } from './tokenChainData.js';
import {
  TokenConfigError,
  tokenConfigErrorSchema,
} from './tokenConfigError.js';
import { TokenMetadata, tokenMetadataSchema } from './tokenMetadata.js';

export interface TokenApiResponse {
  metadata: TokenMetadata;
  /** Token data indexed by token symbol and then by chain ID/selector */
  data: Record<string, TokenChainData>;
  /** List of tokens that were ignored due to configuration issues */
  ignored: TokenConfigError[];
  additionalProperties?: Record<string, unknown>;
}

export const tokenApiResponseSchema: Schema<TokenApiResponse> = lazy(() =>
  typedExpandoObject(
    {
      metadata: ['metadata', tokenMetadataSchema],
      data: ['data', dict(tokenChainDataSchema)],
      ignored: ['ignored', array(tokenConfigErrorSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
