/**
 * CCIP directory and configuration REST API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TokenChainInfoChainId,
  tokenChainInfoChainIdSchema,
} from './containers/tokenChainInfoChainId.js';
import { PoolType, poolTypeSchema } from './poolType.js';

export interface TokenChainInfo {
  /** Identifier of the chain (numeric for EVM chains, string for Solana/Aptos chains) */
  chainId: TokenChainInfoChainId;
  /** Human-readable name of the chain */
  chainName: string;
  /** Token contract address on this chain */
  tokenAddress: string;
  /** Number of decimals used for the token */
  decimals: number;
  /** Type of pool for this token */
  poolType: PoolType;
  /** Token pool contract address (if applicable) */
  poolAddress: string;
  additionalProperties?: Record<string, unknown>;
}

export const tokenChainInfoSchema: Schema<TokenChainInfo> = lazy(() =>
  typedExpandoObject(
    {
      chainId: ['chainId', tokenChainInfoChainIdSchema],
      chainName: ['chainName', string()],
      tokenAddress: ['tokenAddress', string()],
      decimals: ['decimals', number()],
      poolType: ['poolType', poolTypeSchema],
      poolAddress: ['poolAddress', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
